name: Build Lethal Company Mod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build project
        run: dotnet build LethalCompanyTemplate/OverdoseChaos.csproj --configuration Release

      - name: Upload built artifact
        uses: actions/upload-artifact@v4
        with:
          name: OverdoseChaos-Plugin
          path: LethalCompanyTemplate/bin/Release/netstandard2.1/
